[package]
name = "solasm"
version = "0.1.0"
authors = ["g. nicholas d'andrea <nick@gnidan.org>"]
build = "build.rs"

[dependencies]
clap = "2.23.1"
rustc-serialize = "0.3"
bigint = "1.0"
log = "0.3.7"

[dev-dependencies]
env_logger = "0.3"

[build-dependencies]
peg = { version = "0.5" }

[lib]
name = "solasm"

[[bin]]
name = "solasm"
test = false
doc = false

[badges]
travis-ci = { repository = "gnidan/solasm" }
